name: morning_mate
description: A morning diary app with character growth and social features
publish_to: 'none'
version: 0.1.1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # Firebase
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.1
  cloud_firestore: ^5.4.4
  firebase_messaging: ^15.1.3
  cloud_functions: ^5.1.3
  firebase_analytics: ^11.3.3
  firebase_data_connect: ^0.1.3

  
  # State Management
  provider: ^6.1.1
  get: ^4.6.6
  
  # Security
  flutter_secure_storage: ^9.0.0
  encrypt: ^5.0.3
  crypto: ^3.0.3
  local_auth: ^2.1.8
  
  # UI/UX
  animations: ^2.0.11
  lottie: ^3.0.0
  flutter_svg: ^2.0.9
  
  # Routing
  go_router: ^12.1.3
  
  # Utils
  intl: ^0.20.2
  shared_preferences: ^2.2.2
  path_provider: ^2.1.1
  table_calendar: ^3.0.9
  package_info_plus: ^9.0.0
  confetti: ^0.8.0

  #Ads
  google_mobile_ads: ^5.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  flutter_launcher_icons: "^0.13.1"

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/app_icon.png"

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
    - assets/animations/
    - assets/icons/
    - assets/items/
  
  fonts:
    - family: Pretendard
      fonts:
        - asset: assets/fonts/Pretendard-Regular.otf
        - asset: assets/fonts/Pretendard-Bold.otf
          weight: 700
    - family: NanumPenScript-Regular
      fonts:
        - asset: assets/fonts/NanumPenScript-Regular.ttf
    - family: BMJUA
      fonts:
        - asset: assets/fonts/BMJUA_ttf.ttf